- Première partie vérification des routes de l'admin, controller et vues de l'administration effectuée avec succès 
- Deuxième partie  vérification des routes du fichier web, controller et vues  effectuée avec succès
- Troisième partie vérification des routes du fichier profil, controller et vues  à faire